/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:ac586086-f229-4fb9-a23b-26c074d354ff",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_aEm3B1K34",
    "aws_user_pools_web_client_id": "1m7fng69qrkeq1fc2ef1rc2e8s",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://3j7sz7czgbeltbruj4pyjzsm4i.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-uynvzsmkibgh3hhqja7n4dmhpe"
};


export default awsmobile;
